// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crm_backend.DataAccessLayer.EF;

namespace crm_backend.DataAccessLayer.Migrations
{
    [DbContext(typeof(CrmBackendDbContext))]
    [Migration("20201208124459_SeedData4")]
    partial class SeedData4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("crm_backend.DataAccessLayer.Entities.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreateDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = "2019/01/01",
                            Email = "Tien@gmail.com",
                            FirstName = "Duong",
                            LastName = "Tien",
                            Phone = 445334524,
                            Source = "Zip",
                            Status = "Do not call",
                            UpdateDate = "2020/01/01"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = "2019/01/02",
                            Email = "Cuong@gmail.com",
                            FirstName = "Phung",
                            LastName = "Cuong",
                            Phone = 845334524,
                            Source = "rar",
                            Status = "New",
                            UpdateDate = "2020/01/02"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = "2019/01/03",
                            Email = "hoang@gmail.com",
                            FirstName = "Nguyen",
                            LastName = "Hoang",
                            Phone = 884334524,
                            Source = "rar",
                            Status = "Not interested in our Services",
                            UpdateDate = "2020/01/03"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = "2019/01/04",
                            Email = "chau@gmail.com",
                            FirstName = "Chau",
                            LastName = "Nguyen",
                            Phone = 931334524,
                            Source = "rar",
                            Status = "Rented Properties",
                            UpdateDate = "2020/01/04"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = "2019/01/05",
                            Email = "thu@gmail.com",
                            FirstName = "Thu",
                            LastName = "Tran",
                            Phone = 731334524,
                            Source = "rar",
                            Status = "Looking for Rental",
                            UpdateDate = "2020/01/05"
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = "2019/01/06",
                            Email = "Tien@gmail.com",
                            FirstName = "Duong",
                            LastName = "Tien",
                            Phone = 445334524,
                            Source = "Zip",
                            Status = "Do not call",
                            UpdateDate = "2020/01/06"
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = "2019/01/07",
                            Email = "Cuong@gmail.com",
                            FirstName = "Phung",
                            LastName = "Cuong",
                            Phone = 845334524,
                            Source = "rar",
                            Status = "New",
                            UpdateDate = "2020/01/07"
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = "2019/01/08",
                            Email = "hoang@gmail.com",
                            FirstName = "Nguyen",
                            LastName = "Hoang",
                            Phone = 884334524,
                            Source = "rar",
                            Status = "Not interested in our Services",
                            UpdateDate = "2020/01/08"
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = "2019/01/09",
                            Email = "chau@gmail.com",
                            FirstName = "Chau",
                            LastName = "Nguyen",
                            Phone = 931334524,
                            Source = "rar",
                            Status = "Rented Properties",
                            UpdateDate = "2020/01/09"
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = "2019/01/10",
                            Email = "thu@gmail.com",
                            FirstName = "Thu",
                            LastName = "Tran",
                            Phone = 731334524,
                            Source = "rar",
                            Status = "Looking for Rental",
                            UpdateDate = "2020/01/10"
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = "2019/01/11",
                            Email = "Tien@gmail.com",
                            FirstName = "Duong",
                            LastName = "Tien",
                            Phone = 445334524,
                            Source = "Zip",
                            Status = "Do not call",
                            UpdateDate = "2020/01/11"
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = "2019/01/12",
                            Email = "Cuong@gmail.com",
                            FirstName = "Phung",
                            LastName = "Cuong",
                            Phone = 845334524,
                            Source = "rar",
                            Status = "New",
                            UpdateDate = "2020/01/12"
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = "2019/01/13",
                            Email = "hoang@gmail.com",
                            FirstName = "Nguyen",
                            LastName = "Hoang",
                            Phone = 884334524,
                            Source = "rar",
                            Status = "Not interested in our Services",
                            UpdateDate = "2020/01/13"
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = "2019/01/14",
                            Email = "chau@gmail.com",
                            FirstName = "Chau",
                            LastName = "Nguyen",
                            Phone = 931334524,
                            Source = "rar",
                            Status = "Rented Properties",
                            UpdateDate = "2020/01/14"
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = "2019/01/15",
                            Email = "thu@gmail.com",
                            FirstName = "Thu",
                            LastName = "Tran",
                            Phone = 731334524,
                            Source = "rar",
                            Status = "Looking for Rental",
                            UpdateDate = "2020/01/15"
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = "2019/01/16",
                            Email = "Tien@gmail.com",
                            FirstName = "Nguyen",
                            LastName = "Lam",
                            Phone = 445334524,
                            Source = "Zip",
                            Status = "Do not call",
                            UpdateDate = "2020/01/16"
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = "2019/01/17",
                            Email = "Cuong@gmail.com",
                            FirstName = "Doan",
                            LastName = "Cuong",
                            Phone = 845334524,
                            Source = "rar",
                            Status = "New",
                            UpdateDate = "2020/01/17"
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = "2019/01/18",
                            Email = "hoang@gmail.com",
                            FirstName = "Chan",
                            LastName = "Hoang",
                            Phone = 884334524,
                            Source = "rar",
                            Status = "Not interested in our Services",
                            UpdateDate = "2020/01/18"
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = "2019/01/19",
                            Email = "chau@gmail.com",
                            FirstName = "Chau",
                            LastName = "Long",
                            Phone = 931334524,
                            Source = "rar",
                            Status = "Rented Properties",
                            UpdateDate = "2020/01/19"
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = "2019/01/20",
                            Email = "thu@gmail.com",
                            FirstName = "Nguyen",
                            LastName = "Tran",
                            Phone = 731334524,
                            Source = "rar",
                            Status = "Looking for Rental",
                            UpdateDate = "2020/01/20"
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = "2019/01/21",
                            Email = "Tien@gmail.com",
                            FirstName = "Duong",
                            LastName = "Tien",
                            Phone = 445334524,
                            Source = "Zip",
                            Status = "Do not call",
                            UpdateDate = "2020/01/21"
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = "2019/01/22",
                            Email = "Cuong@gmail.com",
                            FirstName = "Anh",
                            LastName = "Cuong",
                            Phone = 845334524,
                            Source = "rar",
                            Status = "New",
                            UpdateDate = "2020/01/22"
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = "2019/01/23",
                            Email = "hoang@gmail.com",
                            FirstName = "Hoang",
                            LastName = "Nhat",
                            Phone = 884334524,
                            Source = "rar",
                            Status = "Not interested in our Services",
                            UpdateDate = "2020/01/23"
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = "2019/01/24",
                            Email = "chau@gmail.com",
                            FirstName = "Ha",
                            LastName = "Nguyen",
                            Phone = 931334524,
                            Source = "rar",
                            Status = "Rented Properties",
                            UpdateDate = "2020/01/24"
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = "2019/01/25",
                            Email = "thu@gmail.com",
                            FirstName = "B",
                            LastName = "Tran",
                            Phone = 731334524,
                            Source = "rar",
                            Status = "Looking for Rental",
                            UpdateDate = "2020/01/25"
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = "2019/01/26",
                            Email = "Tien@gmail.com",
                            FirstName = "Nhat",
                            LastName = "Tien",
                            Phone = 445334524,
                            Source = "Zip",
                            Status = "Do not call",
                            UpdateDate = "2020/01/26"
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = "2019/01/27",
                            Email = "Cuong@gmail.com",
                            FirstName = "Ngoc",
                            LastName = "Long",
                            Phone = 845334524,
                            Source = "rar",
                            Status = "New",
                            UpdateDate = "2020/01/27"
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = "2019/01/28",
                            Email = "hoang@gmail.com",
                            FirstName = "Chinh",
                            LastName = "Hoang",
                            Phone = 884334524,
                            Source = "rar",
                            Status = "Not interested in our Services",
                            UpdateDate = "2020/01/28"
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = "2019/01/29",
                            Email = "chau@gmail.com",
                            FirstName = "Anh",
                            LastName = "Nguyen",
                            Phone = 931334524,
                            Source = "rar",
                            Status = "Rented Properties",
                            UpdateDate = "2020/01/29"
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = "2019/01/30",
                            Email = "thu@gmail.com",
                            FirstName = "Ha",
                            LastName = "Tran",
                            Phone = 731334524,
                            Source = "rar",
                            Status = "Looking for Rental",
                            UpdateDate = "2020/01/30"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
