// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crm_backend.DataAccessLayer.EF;

namespace crm_backend.DataAccessLayer.Migrations
{
    [DbContext(typeof(CrmBackendDbContext))]
    [Migration("20201205081250_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("crm_backend.DataAccessLayer.Entities.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreateDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = "10/11/2020",
                            Email = "ng.d.huy95@gmail.com",
                            FirstName = "Nguyen",
                            LastName = "Huy",
                            Phone = 945334524,
                            Source = "Zip",
                            Status = "Do not call",
                            UpdateDate = "15/11/2020"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = "10/1/2020",
                            Email = "abc@gmail.com",
                            FirstName = "Tran",
                            LastName = "Long",
                            Phone = 545334524,
                            Source = "rar",
                            Status = "New",
                            UpdateDate = "1/11/2020"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = "9/2/2020",
                            Email = "hoa@gmail.com",
                            FirstName = "Hoa",
                            LastName = "Nguyen",
                            Phone = 234334524,
                            Source = "rar",
                            Status = "Not interested in our Services",
                            UpdateDate = "5/12/2020"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = "11/2/2020",
                            Email = "chau@gmail.com",
                            FirstName = "Chau",
                            LastName = "Nguyen",
                            Phone = 931334524,
                            Source = "rar",
                            Status = "Rented Properties",
                            UpdateDate = "5/3/2020"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = "06/07/2020",
                            Email = "thu@gmail.com",
                            FirstName = "Thu",
                            LastName = "Tran",
                            Phone = 731334524,
                            Source = "rar",
                            Status = "Looking for Rental",
                            UpdateDate = "1/8/2020"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
